---
global:
  scrape_interval: 30s

scrape_configs:
    - job_name: node
      scrape_interval: 15s
      static_configs:
        - targets: [ 'node-exporter:9100' ]

    - job_name: app
      scrape_interval: 15s
      static_configs:
        - targets: [ '10.0.2.15:8080' ]